services:
  # --- SHARED INFRA ---
  etcd:
    image: gcr.io/etcd-development/etcd:v3.6.8
    container_name: core-docker-etcd
    command:
      - etcd
      - --name=node-1
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --initial-cluster-token=core-docker-cluster
      - --initial-cluster-state=new
    networks:
      backhaul:
        ipv4_address: 10.0.0.5
    restart: always

  # --- NODE 1 ---
  dind-node1:
    image: docker:dind
    privileged: true
    container_name: core-docker-dind-node1
    networks:
      backhaul:
        ipv4_address: 10.0.0.10
      web-proxy:
    environment:
      - DOCKER_TLS_CERTDIR=

  backend-node1:
    container_name: core-docker-backend-node1
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DOCKER_HOST=tcp://dind-node1:2375
      - SECRET_MANAGER_KEY=6a656d6f6564657269736c656c696a6b656e67616172832746ab37e98f81a3f1
      - ETCD_HOSTS=http://etcd:2379
      - NODE_ID=node-1
      - NODE_NAME=node-1
    depends_on:
      - dind-node1
      - etcd
    networks:
      backhaul:
        ipv4_address: 10.0.0.11
    restart: always

  frontend-node1:
    container_name: core-docker-frontend-node1
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend-node1
    networks:
      backhaul:
        ipv4_address: 10.0.0.12
    restart: always

  proxy-node1:
    image: nginx:latest
    container_name: core-docker-proxy-node1
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend-node1
      - backend-node1
    networks:
      backhaul:
        ipv4_address: 10.0.0.13
    restart: always

  # --- NODE 2 ---
  dind-node2:
    image: docker:dind
    privileged: true
    container_name: core-docker-dind-node2
    networks:
      backhaul:
        ipv4_address: 10.0.0.20
      web-proxy:
    environment:
      - DOCKER_TLS_CERTDIR=

  backend-node2:
    container_name: core-docker-backend-node2
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DOCKER_HOST=tcp://dind-node2:2375
      - SECRET_MANAGER_KEY=6a656d6f6564657269736c656c696a6b656e67616172832746ab37e98f81a3f1
      - ETCD_HOSTS=http://etcd:2379
      - NODE_ID=node-2
      - NODE_NAME=node-2
    depends_on:
      - dind-node2
      - etcd
    networks:
      backhaul:
        ipv4_address: 10.0.0.21
    restart: always

  frontend-node2:
    container_name: core-docker-frontend-node2
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend-node2
    networks:
      backhaul:
        ipv4_address: 10.0.0.22
    restart: always

  proxy-node2:
    image: nginx:latest
    container_name: core-docker-proxy-node2
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend-node2
    networks:
      backhaul:
        ipv4_address: 10.0.0.23
    restart: always

  # --- NODE 3 ---
  dind-node3:
    image: docker:dind
    privileged: true
    container_name: core-docker-dind-node3
    networks:
      backhaul:
        ipv4_address: 10.0.0.30
      web-proxy:
    environment:
      - DOCKER_TLS_CERTDIR=

  backend-node3:
    container_name: core-docker-backend-node3
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DOCKER_HOST=tcp://dind-node3:2375
      - SECRET_MANAGER_KEY=6a656d6f6564657269736c656c696a6b656e67616172832746ab37e98f81a3f1
      - ETCD_HOSTS=http://etcd:2379
      - NODE_ID=node-3
      - NODE_NAME=node-3
    depends_on:
      - dind-node3
      - etcd
    networks:
      backhaul:
        ipv4_address: 10.0.0.31
    restart: always

  frontend-node3:
    container_name: core-docker-frontend-node3
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend-node3
    networks:
      backhaul:
        ipv4_address: 10.0.0.32
    restart: always

  proxy-node3:
    image: nginx:latest
    container_name: core-docker-proxy-node3
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend-node3
    networks:
      backhaul:
        ipv4_address: 10.0.0.33
    restart: always

networks:
  backhaul:
    name: backhaul
    ipam:
      config:
        - subnet: 10.0.0.0/24
  web-proxy:
    name: web-proxy
