services:
  backend:
    container_name: core-docker-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - core-docker-backend-data:/app/data
    environment:
      - ETCD_IMAGE=gcr.io/etcd-development/etcd:v3.6.8
      # Set this to true in production hosts where port 53 is free
      - DNS_PRODUCTION=true
    networks:
      - backhaul
    restart: always

  frontend:
    container_name: core-docker-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    networks:
      - backhaul
    restart: always

networks:
  web-proxy:
    name: web-proxy
  backhaul:
    name: backhaul

volumes:
  core-docker-backend-data:
    name: core-docker-backend-data
