services:
  backend:
    container_name: core-docker-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CERTS_LOCATION:-./nginx/ssl}:/etc/certs:ro
      - ${BACKUP_LOCATION:-./data/backup}:/mnt/backup
      - ${NONBACKUP_LOCATION:-./data/nonbackup}:/mnt/non-backup
    environment:
      - ETCD_IMAGE=${ETCD_IMAGE:-gcr.io/etcd-development/etcd:v3.6.8}
      - NGINX_IMAGE=${NGINX_IMAGE:-nginx:1.25.4-alpine}
      - ALPINE_IMAGE=${ALPINE_IMAGE:-alpine:3.19}
      - DNS_PRODUCTION=true
      - NODE_DOMAIN=${NODE_DOMAIN:-node-1.local}
      - NODE_IP=${NODE_IP:-127.0.0.1}
      - HOST_BACKUP_PATH=${BACKUP_LOCATION:-./data/backup}
      - HOST_NONBACKUP_PATH=${NONBACKUP_LOCATION:-./data/nonbackup}
    group_add:
      - 986 # Host docker group GID
    networks:
      - backhaul
    restart: always
    # Hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /run

  frontend:
    container_name: core-docker-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    networks:
      - backhaul
    restart: always
    # Hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /run

networks:
  web-proxy:
    name: web-proxy
  backhaul:
    name: backhaul
